
export const links = [
    "Home",
    "About",
    "Skill",
    "Project",
    "Contact"
]

export const skillsData = [
    "HTML",
    "CSS",
    "JavaScript",
    "React.js",
    "Express.js",
    "Node.js",
    "Next.js",
    "MongoDB",
    "Tailwind",
    "Shadcn/ui",
    "Git",
    "GitHub",
    "Java",
    "Spring Boot",
    "MySQL",
]

export const projects = [
    {
        id: 1,
        title: "Full Stack E-Commerce",
        img: "https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=600",
        desc1: "Developed using Next.js, Tailwind CSS, Firebase, MongoDB, and Stripe for payments",
        desc2: "Implemented authentication and authorization for admin CRUD operations and client transactions.",
        desc3: "Enabled cart management, address selection, order tracking, and secure payment processing.",    
        tools: ["Next js", "Tailwind", "mongo DB", "Stripe", "Firebase"],    
        github: "https://github.com/Akashyadav18/E_Commerce",
        demo: "https://e-commerce-omega-sepia.vercel.app",
    },
    {
        id: 2,
        title: "Product Catalog",
        img: "https://images.pexels.com/photos/6956800/pexels-photo-6956800.jpeg?auto=compress&cs=tinysrgb&w=600",
        desc1: "Developed an e-commerce style catalog with category-based filtering, product search, and price sorting (asc/desc).",
        desc2: "Integrated Spring Boot REST APIs with a React frontend for seamless data display.",
        desc3: "Optimized backend logic to efficiently handle search and filter conditions.",    
        tools: ["Spring Boot", "Spring Web", "Spring JPA", "MySQL", "Lombok", "React.js", "Tailwind CSS"],    
        github: "https://github.com/Akashyadav18/Next_Blog",
        demo: "",
    },
    {
        id: 3,
        title: "Shopping Cart",
        img: "https://images.pexels.com/photos/1666067/pexels-photo-1666067.jpeg?auto=compress&cs=tinysrgb&w=600",
        desc1: "Implemented an interactive UI ensuring a seamless experience across various devices.",
        desc2: "Utilized browser local storage for persistent user data, enhancing the shopping experience.",
        desc3: "Employed Redux Toolkit for efficient state management, optimized data flow, and scalable application architecture.",        
        tools: ["react", "Next js", "mongo Db", "prisma", "My Sql"],
        github: "https://github.com/Akashyadav18/shopping-UI",
        demo: "",
    },
    {
        id: 4,
        title: "Note Taker App",
        img: "https://images.pexels.com/photos/2034373/pexels-photo-2034373.jpeg?auto=compress&cs=tinysrgb&w=600",
        desc1: "Engineered a robust note-taker application with secure user authentication and comprehensive note lifecycle management (add, update, delete, status tracking)",
        desc2: "Ensured automated data integrity by intelligently handling relational dependencies, preventing orphaned records when users were removed.",
        desc3: "Deployed on Render using Docker image and PostgreSQL, ensuring scalability and production readiness.",        
        tools: ["Spring Boot", "Spring Web", "JPA", "MySQL", "Thymeleaf", "Bootstrap", "Docker", "PostgreSQL"],
        github: "https://github.com/Akashyadav18/SpringBoot_NoteApp",
        demo: "https://noteapp-qj78.onrender.com/",
    },
    {
        id: 5,
        title: "Employee Management System",
        img: "https://images.pexels.com/photos/7433854/pexels-photo-7433854.jpeg?auto=compress&cs=tinysrgb&w=600",
        desc1: "Designed a CRUD-based system for managing employee data with DTOs and mapper classes to improve backend security.",
        desc2: "Implemented RESTful APIs in Spring Boot and connected them with a React frontend.",
        desc3: "Strengthened understanding of backend–frontend data flow and application architecture.",        
        tools: ["Spring Boot", "Spring Web"," JPA", "MySQL", "Lombok", "React.js", "Bootstrap"],
        github: "https://github.com/Akashyadav18/shopping-UI",
        demo: "",
    },
    
]